# Generated by Django 4.2.5 on 2023-09-19 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=200)),
                ('quote', models.CharField(max_length=30)),
                ('acent_img_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='blogSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titles', models.CharField(max_length=200, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('entryDate', models.DateField(auto_now_add=True)),
                ('min_img_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='entryBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('entryDate', models.DateField(auto_now_add=True)),
                ('slug', models.CharField(max_length=200, unique=True)),
            ],
        ),
    ]
