# Generated by Django 4.2.5 on 2023-09-20 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoderBlogApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='entryBlog',
            new_name='EntryBlogData',
        ),
    ]
