# Generated by Django 4.2.5 on 2023-09-20 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoderBlogApp', '0002_rename_entryblog_entryblogdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogsummary',
            old_name='titles',
            new_name='title',
        ),
    ]
