# Generated by Django 4.2.5 on 2023-09-20 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoderBlogApp', '0003_rename_titles_blogsummary_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='hero_img_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='acent_img_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='blogsummary',
            name='min_img_url',
            field=models.URLField(blank=True),
        ),
    ]
