# Generated by Django 4.2.5 on 2023-09-23 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoderBlogApp', '0004_blog_hero_img_url_alter_blog_acent_img_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='post',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='blog',
            name='quote',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='blogsummary',
            name='description',
            field=models.TextField(max_length=200),
        ),
    ]
