# Generated by Django 4.2.5 on 2023-09-23 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoderBlogApp', '0006_alter_blog_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='quote',
            field=models.TextField(max_length=100),
        ),
    ]
