# Generated by Django 4.2.5 on 2023-09-23 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoderBlogApp', '0007_alter_blog_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='post',
            field=models.TextField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='blogsummary',
            name='author',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='blogsummary',
            name='description',
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name='entryblogdata',
            name='author',
            field=models.CharField(max_length=40),
        ),
    ]
