# Generated by Django 4.2.5 on 2023-09-23 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoderBlogApp', '0008_alter_blog_post_alter_blogsummary_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='quote',
            field=models.TextField(max_length=200),
        ),
    ]
